name: Build and Push devenv-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devenv-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devenv-image
        run: nix build -L .#devenv-image

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load and push image
        run: |
          # Load the image from the tarball
          docker load < result

          # Get the image ID from the loaded image
          IMAGE_ID=$(docker images --format "{{.ID}}" | head -n 1)

          # Generate tags
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Also tag with SHA for versioning
          SHA_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          # Tag the image
          docker tag $IMAGE_ID $IMAGE_TAG
          docker tag $IMAGE_ID $SHA_TAG

          # Push both tags
          docker push $IMAGE_TAG
          docker push $SHA_TAG